export const LOAD_CLIENTS_FULFILLED = "LOAD_CLIENTS_FULFILLED";
export const LOAD_CLIENTS_REJECTED = "LOAD_CLIENTS_REJECTED";
export const LOAD_CLIENTS_PENDING = "LOAD_CLIENTS_PENDING";
export const SELECT_CLIENTS = "SELECT_CLIENTS";
export const SEARCH_CLIENTS = "SEARCH_CLIENTS";
