export const LOAD_CLIENTS_FULFILLED = "LOAD_CLIENTS_FULFILLED";
export const LOAD_CLIENTS_REJECTED = "LOAD_CLIENTS_REJECTED";
export const LOAD_CLIENTS_PENDING = "LOAD_CLIENTS_PENDING";
export const SEARCH_CLIENTS = "SEARCH_CLIENTS";
export const SELECT_CLIENT = "SELECT_CLIENT";
